#!/usr/bin/env -S python3 -u

import argparse

parser = argparse.ArgumentParser()
parser.add_argument("zipfile")
args = parser.parse_args()

import seamless
from seamless.config import AssistantConnectionError

try:
    seamless.delegate(raise_exceptions=True)
except AssistantConnectionError:
    try:
        seamless.delegate(level=3, raise_exceptions=True)
    except Exception:
        has_err = seamless.delegate(level=2)
        if has_err:
            exit(1)

from seamless.checksum.buffer_cache import buffer_cache

from seamless.workflow import Context

ctx = Context()
checksums = ctx.add_zip(args.zipfile, incref=True)
print("Added {} buffers".format(len(checksums)))
for checksum in checksums:
    buffer_cache.decref(bytes.fromhex(checksum))
