{% set version = "0.11.1" %}
package:
    name: seamless-cli
    version: {{ version }}

build:
  number: 2
  noarch: python

requirements:
  build:
    - python
  run:
    - openssl
    - ruamel.yaml
    - psutil
about:
  summary: This is a collection of bash scripts wrapping the Seamless Docker image.
