{% set version = "0.8.3" %}
package:
    name: seamless-cli
    version: {{ version }}

build:
  number: 1
  noarch: python

requirements:
  build:
    - python
  run:
    - openssl
    - ruamel.yaml
about:
  summary: This is a collection of bash scripts wrapping the Seamless Docker image.
