# version of meta.yaml for rattler-build. Keep in sync

package:
  name: seamless-cli
  version: "0.13"

build:
  number: 1
  noarch: python

requirements:
  build:
    - python
  run:
    - openssl
    - psutil
    - peewee
    - sqlite

about:
  summary: This is a collection of bash scripts wrapping the Seamless Docker image.
