#!/bin/bash

# modifies a conda environment in the seamless-minimal Docker image
# $1: the environment dir
# $2: the environment.yml file to modify with

set -u -e

CONDA_ENV_DIR=$1
yaml=$(python -c "import sys, os; print(os.path.realpath(sys.argv[1]))" $2)

docker run \
  --rm \
  -it \
  -u `id -u` \
  -e yaml=$yaml \
  -v $CONDA_ENV_DIR:/SEAMLESS-CONDA-ENV \
  -v $yaml:/env.yaml \
  rpbs/seamless-minimal \
  bash -i -c '''
  echo "conda activate /SEAMLESS-CONDA-ENV" >> /.bashrc
  echo "export CONDA_PKGS_DIRS=/SEAMLESS-CONDA-ENV" >> /.bashrc
  bash -c -i "mamba env update --file /env.yaml"
  '''
