#!/bin/bash

set -e
currdir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0`
cd $currdir
source ./seamless-delegate-stop

set -u -e

docker pull rpbs/seamless

if [[ -e delegate ]]; then
    cd delegate
else
    cd $CONDA_PREFIX/share/seamless-cli/delegate
fi

docker compose build hashserver database micro-assistant mini-assistant micro-dask-assistant mini-dask-assistant minifront-dask-assistant

conda update -c rpbs -c conda-forge seamless-cli -y

