#!/bin/bash

# Loads a Seamless project in IPython inside the Seamless Docker image

set -e

currdir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0`
source $currdir/seamless-fill-environment-variables
$currdir/seamless-detect-used-ports 5813 5138

if [ -z "$1" ]; then
  workdir=/cwd
else 
  relpath=`python3 -c 'import os,sys;print(os.path.relpath(sys.argv[1], os.getcwd()))' $1`
  workdir=/cwd/$relpath
fi

set -u -e

containerID=$(docker run --rm -it -d \
  $SEAMLESS_DOCKER_PUBLISH_SHARESERVER_PORTS \
  $SEAMLESS_DOCKER_RUN_PARAMS_X_NAME \
  $SEAMLESS_DOCKER_RUN_PARAMS_X_NETWORK \
  $SEAMLESS_DOCKER_RUN_PARAMS_X_DEVEL \
  -e DOCKER_IMAGE=$SEAMLESS_DOCKER_IMAGE \
  -e DOCKER_VERSION="$SEAMLESS_DOCKER_VERSION" \
  -e HOSTCWD=`pwd` \
  -e SHARESERVER_ADDRESS=$SEAMLESS_SHARESERVER_ADDRESS \
  -e SEAMLESS_READ_BUFFER_FOLDERS=$SEAMLESS_READ_BUFFER_FOLDERS \
  -e SEAMLESS_READ_BUFFER_SERVERS=$SEAMLESS_READ_BUFFER_SERVERS \
  -e SEAMLESS_WRITE_BUFFER_SERVER=$SEAMLESS_WRITE_BUFFER_SERVER \
  -e SEAMLESS_DOCKER_HOST_IP=$SEAMLESS_DOCKER_HOST_IP \
  -e SEAMLESS_DATABASE_IP=$SEAMLESS_DATABASE_IP \
  -e SEAMLESS_DATABASE_PORT=$SEAMLESS_DATABASE_PORT \
  -e SEAMLESS_ASSISTANT_IP=$SEAMLESS_ASSISTANT_IP \
  -e SEAMLESS_ASSISTANT_PORT=$SEAMLESS_ASSISTANT_PORT \
  -e SEAMLESS_ASSISTANT_ID=$SEAMLESS_ASSISTANT_ID \
  -e SEAMLESS_SCRIPTS_DIR=/home/jovyan/seamless-scripts \
  -v `pwd`:/cwd \
  --workdir $workdir \
  -v /tmp:/tmp \
  -u `id -u` \
  --group-add users \
  $SEAMLESS_DOCKER_CUSTOM_PARAMS \
  $SEAMLESS_DOCKER_IMAGE start.sh ipython3 -i -c '%run -i load-project.py
await load()')

echo $containerID | docker exec -i $containerID /bin/bash -c 'cat > /home/jovyan/DOCKER_CONTAINER'
docker attach $containerID