#!/bin/bash

set -e

currdir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0`
source $currdir/seamless-fill-environment-variables

set -u -e

# - Current directory is mounted to /cwd, and the command is executed there

zipfile_dir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $1`
if [[ "$zipfile_dir" =~ ^/home/jovyan/.* ]]; then
  zipfile_name=$1
else
  zipfile_name=${1##*/}

  cd ${zipfile_dir}
fi

$currdir/_seamless_run seamless-upload-zip ${zipfile_name}
