#!/usr/bin/env python3

"""
Reverse proxy code adapted from:
https://github.com/oetiker/aio-reverse-proxy/blob/master/paraview-proxy.py'
(Copyright (c) 2018 Tobias Oetiker, MIT License)
"""

from aiohttp import web
from aiohttp import client
import aiohttp_cors
import aiohttp
import asyncio
import logging
import pprint

#logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Hard-coded canonical Seamless ports
port = 5388
http_destination = "http://localhost:5813/"
ws_destination = "ws://localhost:5138/"

async def handler(req):
    tail = req.match_info.get('tail')
    reqH = req.headers.copy()
    
    # handle the websocket request
    
    if reqH.get('connection') == 'Upgrade' and reqH.get('upgrade') == 'websocket' and req.method == 'GET':

      ws_server = web.WebSocketResponse()
      await ws_server.prepare(req)
      logger.info('##### WS_SERVER %s' % pprint.pformat(ws_server))

      client_session = aiohttp.ClientSession(cookies=req.cookies)
      url = ws_destination + tail
      async with client_session.ws_connect(
        url,
      ) as ws_client:
        logger.info('##### WS_CLIENT %s' % pprint.pformat(ws_client))

        async def ws_forward(ws_from,ws_to):
          async for msg in ws_from:
            #logger.info('>>> msg: %s',pprint.pformat(msg))
            mt = msg.type
            md = msg.data
            if mt == aiohttp.WSMsgType.TEXT:
              await ws_to.send_str(md)
            elif mt == aiohttp.WSMsgType.BINARY:
              await ws_to.send_bytes(md)
            elif mt == aiohttp.WSMsgType.PING:
              await ws_to.ping()
            elif mt == aiohttp.WSMsgType.PONG:
              await ws_to.pong()
            elif ws_to.closed:
              await ws_to.close(code=ws_to.close_code,message=msg.extra)
            else:
              raise ValueError('unexpected message type: %s',pprint.pformat(msg))

        # keep forwarding websocket data in both directions
        coro1 = ws_forward(ws_server,ws_client)
        coro2 = ws_forward(ws_client,ws_server)
        fut1 = asyncio.ensure_future(coro1)
        fut2 = asyncio.ensure_future(coro2)
        await asyncio.wait([fut1, fut2],return_when=asyncio.FIRST_COMPLETED)

        return ws_server
    else:
      # handle normal requests by passing them on downstream
      url = http_destination + tail
      async with client.request(
          req.method, url,
          headers = reqH,
          params=req.query,
          allow_redirects=False,
          data = await req.read()
      ) as res:
          headers = res.headers.copy()
          body = await res.read()
          return web.Response(
            headers = headers,
            status = res.status,
            body = body
          )

app = web.Application(
    client_max_size=1024**3
)
app.add_routes([
    web.get('/{tail:.*}', handler),
    web.put('/{tail:.*}', handler),
    web.patch('/{tail:.*}', handler),
])

'''
# currently bugged... hopefully unnecessary

cors = aiohttp_cors.setup(app, defaults={
    "*": aiohttp_cors.ResourceOptions(
            allow_credentials=True,
            expose_headers="*",
            allow_headers="*",
            allow_methods=["GET", "PATCH", "PUT"]
        )
})

# Configure CORS on all routes.
for route in list(app.router.routes()):
    cors.add(route)    
'''

if __name__ == "__main__":
    web.run_app(app,port=port)
