#!/bin/bash

if [ -z "$SEAMLESS_DOCKER_IMAGE" ]; then
  export SEAMLESS_DOCKER_IMAGE=rpbs/seamless
fi

docker --version && export SEAMLESS_DOCKER_VERSION=$(docker --version)

if [ -z "$SEAMLESS_DOCKER_HOST_IP" ]; then

  docker --version && export SEAMLESS_DOCKER_HOST_IP=$(docker network inspect bridge \
  | python3 -c '''
import json, sys
bridge = json.load(sys.stdin)
print(bridge[0]["IPAM"]["Config"][0]["Gateway"])
''')

fi

function mapping() {
python -c 'import sys
from urllib.parse import urlsplit, urlunsplit
url = list(urlsplit(sys.argv[1]))
docker_host_ip = sys.argv[2]
for w in ("localhost", "127.0.0.1", "127.0.1.1"):
    url[1] = url[1].replace(w, docker_host_ip)
    url[2] = url[2].replace(w, docker_host_ip)
print(urlunsplit(url)) 
' $1 $2
}

if [ -n "$SEAMLESS_CONDA_ENVIRONMENT" ]; then
  if [ -n "$SEAMLESS_DOCKER_HOST_IP" ]; then
    unset SEAMLESS_READ_BUFFER_FOLDERS
    if [ -n "$SEAMLESS_READ_BUFFER_SERVERS" ]; then
      export SEAMLESS_READ_BUFFER_SERVERS=$(mapping $SEAMLESS_READ_BUFFER_SERVERS $SEAMLESS_DOCKER_HOST_IP)
    fi
    if [ -n "$SEAMLESS_WRITE_BUFFER_SERVER" ]; then
      export SEAMLESS_WRITE_BUFFER_SERVER=$(mapping $SEAMLESS_WRITE_BUFFER_SERVER $SEAMLESS_DOCKER_HOST_IP)
    fi
    if [ -n "$SEAMLESS_DATABASE_IP" ]; then 
      export SEAMLESS_DATABASE_IP=$(mapping $SEAMLESS_DATABASE_IP $SEAMLESS_DOCKER_HOST_IP)
    fi
  fi
fi

if [ -z "$SEAMLESS_DEBUGGING_DIRECTORY" ]; then 
  export SEAMLESS_DEBUGGING_DIRECTORY=/tmp/seamless-debug
  mkdir -p ${SEAMLESS_DEBUGGING_DIRECTORY}
fi

if [ -z "$SEAMLESS_DATABASE_IP" ]; then
  export SEAMLESS_DATABASE_IP=$SEAMLESS_DOCKER_HOST_IP
fi

if [ -z "$SEAMLESS_DATABASE_PORT" ]; then
  export SEAMLESS_DATABASE_PORT=5522
fi

if [ -z "$SEAMLESS_ASSISTANT_IP" ]; then
  export SEAMLESS_ASSISTANT_IP=$SEAMLESS_DOCKER_HOST_IP
fi

if [ -z "$SEAMLESS_ASSISTANT_PORT" ]; then
  export SEAMLESS_ASSISTANT_PORT=5533
fi

if [ -z "$SEAMLESS_ASSISTANT_ID" ]; then
  export SEAMLESS_ASSISTANT_ID=""
fi

if [ -z "$SEAMLESS_SHARESERVER_ADDRESS" ]; then
  export SEAMLESS_SHARESERVER_ADDRESS=0.0.0.0
fi

if [ -z "$SEAMLESS_READ_BUFFER_FOLDERS" ]; then
  export SEAMLESS_READ_BUFFER_FOLDERS=''
fi

if [ -z "$DOCKER_IMAGE" ]; then
  if [ -z "$SEAMLESS_CONFIG_DIRECTORY" ]; then
    export SEAMLESS_CONFIG_DIRECTORY=$HOME/.seamless
  fi
fi

if [ -z "$SEAMLESS_HASHSERVER_PORT" ]; then
  export SEAMLESS_HASHSERVER_PORT=5577
fi

if [ -z "$SEAMLESS_READ_BUFFER_SERVERS" ]; then
  export SEAMLESS_READ_BUFFER_SERVERS='http://'$SEAMLESS_DOCKER_HOST_IP':'$SEAMLESS_HASHSERVER_PORT
fi

if [ -z "$SEAMLESS_WRITE_BUFFER_SERVER" ]; then
  export SEAMLESS_WRITE_BUFFER_SERVER='http://'$SEAMLESS_DOCKER_HOST_IP':'$SEAMLESS_HASHSERVER_PORT
fi

if [ -z "$SEAMLESS_DOCKER_RUN_PARAMS_X_NETWORK" ]; then
  export SEAMLESS_DOCKER_RUN_PARAMS_X_NETWORK='--network=bridge'
fi

export SEAMLESS_DOCKER_RUN_PARAMS_X_TRUSTED="""-v /var/run/docker.sock:/var/run/docker.sock \
--group-add $(getent group docker | cut -d: -f3)"""

export SEAMLESS_DOCKER_RUN_PARAMS_X_DEVEL='' 
if [ "$SEAMLESS_DOCKER_IMAGE" == seamless-devel ]; then
  if [ -z "$SEAMLESSDIR" ]; then
    echo 'SEAMLESSDIR undefined'
    exit 1
  fi
  export SEAMLESS_DOCKER_RUN_PARAMS_X_DEVEL="-v $SEAMLESSDIR:/seamless -e PYTHONPATH=/silk:/seamless"
  if [ -z "$SILKDIR" ]; then
      echo 'SILKDIR undefined, using conda-installed version' > /dev/stderr
  else
    export SEAMLESS_DOCKER_RUN_PARAMS_X_DEVEL="-v $SEAMLESSDIR:/seamless -v $SILKDIR:/silk -e PYTHONPATH=/silk:/seamless"
  fi
  if [ -z "$SEAMLESS_TOOLS_DIR" ]; then
      echo 'SEAMLESS_TOOLS_DIR undefined, using Docker-installed version' > /dev/stderr
  else
    export SEAMLESS_DOCKER_RUN_PARAMS_X_DEVEL=$SEAMLESS_DOCKER_RUN_PARAMS_X_DEVEL" -v $SEAMLESS_TOOLS_DIR/tools:/home/jovyan/seamless-tools  -v $SEAMLESS_TOOLS_DIR/scripts:/home/jovyan/seamless-scripts -v $SEAMLESS_TOOLS_DIR/seamless-cli:/home/jovyan/seamless-cli -v $SEAMLESSDIR/bin:/home/jovyan/seamless-bin"
  fi
fi

export SEAMLESS_DOCKER_RUN_PARAMS_X_NAME=''

if [ -n "$SEAMLESS_DOCKER_CONTAINER_NAME" ]; then
    export SEAMLESS_DOCKER_RUN_PARAMS_X_NAME="--name $SEAMLESS_DOCKER_CONTAINER_NAME"
fi

if [ -z ${SEAMLESS_DOCKER_PUBLISH_SHARESERVER_PORTS+x} ]; then
  export SEAMLESS_DOCKER_PUBLISH_SHARESERVER_PORTS="""-p 5813:5813 \
-p 5138:5138"""
fi

if [ -z ${SEAMLESS_JUPYTER_PORT} ]; then
  export SEAMLESS_JUPYTER_PORT=8888
fi
if [ -z ${SEAMLESS_DOCKER_PUBLISH_JUPYTER_PORTS+x} ]; then
  export SEAMLESS_DOCKER_PUBLISH_JUPYTER_PORTS="-p $SEAMLESS_JUPYTER_PORT:$SEAMLESS_JUPYTER_PORT"
fi

if [ -z ${SEAMLESS_DOCKER_PUBLISH_DEBUG_PORTS+x} ]; then
  export SEAMLESS_DOCKER_PUBLISH_DEBUG_PORTS="-p 5679-5685:5679-5685"
fi

if [ -z "$SEAMLESS_DOCKER_CUSTOM_PARAMS" ]; then
  export SEAMLESS_DOCKER_CUSTOM_PARAMS=""
fi

export HOST_USER_ID=`id -u`
export HOST_GROUP_ID=`id -g`

if [ -z "$_SEAMLESS_FILL_ENVIRONMENT_VARIABLES_NO_PRINTENV" ]; then

printenv | sort | python3 -c '''
import sys
for l in sys.stdin.readlines():
  ll = l.split("=")
  if len(ll) == 2 and not len(ll[1].strip()):
    continue
  if ll[0].find("SEAMLESS") > -1 and ll[0].find("__CONDA") == -1: 
    print(l,end="",file=sys.stderr)
'''

fi