#!/bin/bash

set -e

currdir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0`
source $currdir/seamless-fill-environment-variables

set -u -e

vault_dir=`python3 -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' $1`
shift 1

$currdir/_seamless_run seamless-upload-vault $vault_dir $*