#!/bin/bash

set -e

args=""
for var in "$@"
do
    args="$args \"$var\""
done

currdir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0`
source $currdir/seamless-fill-environment-variables

set -u -e

docker run --rm \
  $SEAMLESS_DOCKER_RUN_PARAMS_X_NAME \
  $SEAMLESS_DOCKER_RUN_PARAMS_X_NETWORK \
  $SEAMLESS_DOCKER_RUN_PARAMS_X_DEVEL \
  -e DOCKER_IMAGE=$SEAMLESS_DOCKER_IMAGE \
  -e DOCKER_VERSION="$SEAMLESS_DOCKER_VERSION" \
  -e HOSTCWD=`pwd` \
  -e SHARESERVER_ADDRESS=$SEAMLESS_SHARESERVER_ADDRESS \
  -e SEAMLESS_READ_BUFFER_FOLDERS=$SEAMLESS_READ_BUFFER_FOLDERS \
  -e SEAMLESS_READ_BUFFER_SERVERS=$SEAMLESS_READ_BUFFER_SERVERS \
  -e SEAMLESS_WRITE_BUFFER_SERVER=$SEAMLESS_WRITE_BUFFER_SERVER \
  -e SEAMLESS_DOCKER_HOST_IP=$SEAMLESS_DOCKER_HOST_IP \
  -e SEAMLESS_DATABASE_IP=$SEAMLESS_DATABASE_IP \
  -e SEAMLESS_DATABASE_PORT=$SEAMLESS_DATABASE_PORT \
  -e SEAMLESS_ASSISTANT_IP=$SEAMLESS_ASSISTANT_IP \
  -e SEAMLESS_ASSISTANT_PORT=$SEAMLESS_ASSISTANT_PORT \
  -e SEAMLESS_SCRIPTS_DIR=/home/jovyan/seamless-scripts \
  -v `pwd`:/cwd \
  --workdir /cwd \
  -v /tmp:/tmp \
  -u `id -u` \
  --group-add users \
  $SEAMLESS_DOCKER_CUSTOM_PARAMS \
  $SEAMLESS_DOCKER_IMAGE bash -ic "$args"
  #$SEAMLESS_DOCKER_IMAGE bash -ic "$1 $2 \"$3\" \"$4\""
  #$SEAMLESS_DOCKER_IMAGE bash -ic "seamless -vvv -c \"echo 42 ; echo 88; ls; date\""
