channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - conda=4.12
  - numpy==1.21.*
  - requests==2.28.*
  - cffi==1.14.*
  - traitlets==5.4.*
  - ruamel.yaml==0.17.*
  - ruamel.yaml.clib==0.2.*
  - jsonschema==3.2.*
  - aiohttp==3.7.*
  - multidict==5.1.*
  - wurlitzer==3.0.*
  - yarl==1.6.*
  - pandas==1.3.*
  - IPython==8.5.*
  - notebook==6.4.*
  - ipykernel==6.15.*
  - pyzmq==24.0.*
  - jedi==0.18.*
  - parso==0.8.*
  - aiofiles==0.8.*
  - cython==0.29.*
  - r-base==4.0.*
  - r-cairo==1.5_12.*
  - rpy2==3.4.*
  - commentjson==0.9.*
  - jupyter-server-proxy==3.2.*
  - aiofiles==0.8.*
  - async-timeout==3.0.*
  - rpbs::silk
  - mamba
  - openmp
  - pip:
    - nglview
    - snakemake
    - cson==0.8
    - speg==0.3
    - websockets==10.3
    - aiohttp_cors==0.7.*
    - jupyter-console==6.4.*
    - docker==6.0.*
    - itables==1.3.*
    - debugpy==1.6.*
    - tornado==6.2.*
    - orjson

variables:
    RPY2_CFFI_MODE: ABI
