channels:
  - conda-forge
dependencies:
  # keep this in sync with seamless/conda/seamless-exact-environment.yml

  # from jupyter/base-notebook, essential (all of Seamless won't work)
  - python=3.10.*
  - conda=23.1.*
  - ruamel.yaml=0.17.*
  - psutil=5.9.*
  - jinja2=3.1.*
  - traitlets=5.9.*
  - jsonschema=4.18.*  # for silk

  # from jupyter/base-notebook, recommended (parts of Seamless won't work)
  - ipython=8.15.*
  - ipykernel=6.21.*

  - cffi=1.15.*  
  - ipywidgets=8.0.*
  - debugpy=1.6.*
  
  # from jupyter/base-notebook, support packages
  - mamba=1.3.*
  - pip=23.0.*
  - notebook=6.5.*
  - jupyterhub=3.1.*
  - jupyterlab=3.6.*

  # new packages: essential (all or most of Seamless won't work)
  - numpy=1.24.*  
  - orjson=3.8.*
  - requests=2.31.*
  - aiohttp=3.7.*
  - bashlex=0.18.*
  - datrie  # required to build some pip packages

  # new packages: recommended (parts of Seamless won't work)
  - openmp=8.0.*
  - wurlitzer=3.0.*
  - cython=0.29.*
  - commentjson
  - expandvars
  - rpbs::seamless-cli
  
  # new packages: support packages
  - scipy
  - pandas
  - r-base=4.2.*
  - scikit-learn=1.2.*
  - r-cairo=1.6_0.*
  - rpy2==3.5.*
  - sympy

  - pip:
    # essential (all or most of Seamless won't work)
    - websockets==10.3.*
    - cson==0.8.*
    - speg
    - aiohttp_cors==0.7.*
    # recommended (parts of Seamless won't work)
    - docker==7.0.*
    - makefun
    # support packages
    - nglview
    - matplotlib  # installs much fewer dependencies than conda
    - snakemake==7.18.*
    - jupyter-console==6.6.*
    - itables==1.4.*
    # - jsonschema==4.18.*  # for silk; repeat in Dockerfile

variables:
    RPY2_CFFI_MODE: ABI
