{% set version = "0.13" %}
package:
    name: seamless-cli-complement
    version: {{ version }}

build:
  number: 1
  noarch: python

requirements:
  build:
    - python
  run:
    - openssl
    - psutil
    - peewee
    - sqlite
    - aiohttp
about:
  summary: This is a collection of bash scripts wrapping the Seamless Docker image.
