#!/bin/bash -i

set -u -e

# clones the conda environment to the specified directory

currdir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0`

CONDA_ENV_INPUT_DIR=$1
CONDA_ENV_OUTPUT_DIR=$2
rm -rf $CONDA_ENV_OUTPUT_DIR

export CONDA_PKGS_DIRS=$CONDA_ENV_OUTPUT_DIR
mamba create --prefix $CONDA_ENV_OUTPUT_DIR --clone $CONDA_ENV_INPUT_DIR --force || exit 1

#KLUDGE: for some reason, seamless-framework cannot be cloned out of the root environment
conda activate base
PKG=$(conda list -n $CONDA_ENV_INPUT_DIR 'seamless-framework|^conda$' --export | grep -v '#')
mamba install --prefix $CONDA_ENV_OUTPUT_DIR -c rpbs -c conda-forge $PKG -y