#!/bin/bash

set -u -e

# exports the default seamless-minimal conda environment
# (defined in /seamless-minimal/environment.yml)
# to the specified directory
# NOTE: exported directories can be backed up with cp -r
# but when executed, they must run under the original directory name

currdir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0`

CONDA_ENV_OUTPUT_DIR=`python3 -c '''
import sys, os
x = sys.argv[1]
if not x.startswith(os.sep): 
  x = "." + os.sep + x
print(x)''' $1`
rm -rf $CONDA_ENV_OUTPUT_DIR
mkdir -p $CONDA_ENV_OUTPUT_DIR

HOMEDIR=$(mktemp -d /tmp/temphome-XXXXXXXXXX)
cp $currdir/dummy-bashrc $HOMEDIR/.bashrc

singularity run \
   --cleanenv \
   --containall \
   --bind $CONDA_ENV_OUTPUT_DIR:/SEAMLESS-CONDA-ENV:rw \
   --home $HOMEDIR \
   --bind /tmp:/tmp \
   $SEAMLESS_MINIMAL_SINGULARITY_IMAGE bash -c -i '''
   conda activate
   cp /seamless-minimal/environment.yml /tmp
   export CONDA_PKGS_DIRS=/SEAMLESS-CONDA-ENV
   mamba env create --prefix /SEAMLESS-CONDA-ENV --file /tmp/environment.yml || exit 1
   '''

singularity run \
  --cleanenv \
  --containall \
  --bind $CONDA_ENV_OUTPUT_DIR:/SEAMLESS-CONDA-ENV:rw \
  --home $HOMEDIR \
  --bind /tmp:/tmp \
  $SEAMLESS_MINIMAL_SINGULARITY_IMAGE bash -c -i '''
  conda activate; conda activate /SEAMLESS-CONDA-ENV 
  export CONDA_PKGS_DIRS=/SEAMLESS-CONDA-ENV
  mamba repoquery search conda -c conda-forge -c main
  '''

chmod -R a+r $CONDA_ENV_OUTPUT_DIR

rm -rf $HOMEDIR