#!/bin/bash

set -u -e

# modifies a conda environment in the seamless-minimal Docker image
# $1: the environment dir
# $2: the environment.yml file to modify with

currdir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0`

CONDA_ENV_OUTPUT_DIR=$1
rm -rf $CONDA_ENV_OUTPUT_DIR
mkdir -p $CONDA_ENV_OUTPUT_DIR

HOMEDIR=$(mktemp -d /tmp/temphome-XXXXXXXXXX)
cp $currdir/dummy-bashrc $HOMEDIR/.bashrc

singularity run \
   --cleanenv \
   --containall \
   --bind $CONDA_ENV_OUTPUT_DIR:/SEAMLESS-CONDA-ENV:rw \
   --home $HOMEDIR \
   $SEAMLESS_MINIMAL_SINGULARITY_IMAGE bash -c -i '''
   conda activate
   cp /seamless-minimal/environment.yml /tmp
   export CONDA_PKGS_DIRS=/SEAMLESS-CONDA-ENV
   mamba env create --prefix /SEAMLESS-CONDA-ENV --file /tmp/environment.yml || exit 1
   '''

singularity run \
  --cleanenv \
  --containall \
  --bind $CONDA_ENV_OUTPUT_DIR:/SEAMLESS-CONDA-ENV:rw \
  --home $HOMEDIR \
  --bind /tmp:/tmp \
  $SEAMLESS_MINIMAL_SINGULARITY_IMAGE bash -c -i '''
  conda activate; conda activate /SEAMLESS-CONDA-ENV 
  export CONDA_PKGS_DIRS=/SEAMLESS-CONDA-ENV
  mamba repoquery search conda -c conda-forge -c main
  '''

chmod -R a+r $CONDA_ENV_OUTPUT_DIR

rm -rf $HOMEDIR