services:
  database:
    build:
      context: ../../tools
      dockerfile: database.Dockerfile
    user: ${HOST_USER_ID:?}:${HOST_GROUP_ID:?}
    ports:
      - ${DATABASE_PORT:?}:${DATABASE_PORT:?}
    environment:
      - DATABASE_HOST=0.0.0.0
      - DATABASE_PORT=${DATABASE_PORT:?}
      - DATABASE_WRITABLE=1    
    volumes:
      - ${SEAMLESS_CONFIG_DIRECTORY:?}/database:/database
  hashserver:
    build: 
      context: ../hashserver
    user: ${HOST_USER_ID:?}:${HOST_GROUP_ID:?}
    ports:
      - ${HASHSERVER_PORT:?}:${HASHSERVER_PORT:?}
    environment:
      - HASHSERVER_HOST=0.0.0.0
      - HASHSERVER_PORT=${HASHSERVER_PORT:?}
      - HASHSERVER_WRITABLE=1    
    volumes:
      - ${SEAMLESS_CONFIG_DIRECTORY:?}/buffers:/buffers
  micro-assistant-devel:
      build:
        context: ../../scripts
        dockerfile: micro-assistant-devel.Dockerfile
      user: ${HOST_USER_ID:?}:${HOST_GROUP_ID:?}
      ports:
        - ${SEAMLESS_ASSISTANT_PORT:?}:${SEAMLESS_ASSISTANT_PORT:?}
      volumes:
        - ${SEAMLESSDIR:?}:/seamless
        - ${SEAMLESS_TOOLS_DIR:?}/tools:/home/jovyan/seamless-tools
        - ${SEAMLESS_TOOLS_DIR:?}/scripts:/home/jovyan/seamless-scripts
        - ${SEAMLESS_TOOLS_DIR:?}/seamless-cli:/home/jovyan/seamless-cli
        - ${SILKDIR:?}:/silk
        - /var/run/docker.sock:/var/run/docker.sock # Docker access
        - /tmp:/tmp  # temp dir to execute Docker transformers in
      group_add: 
        - users
        - ${DOCKER_GROUP_ID:?}
      environment:
        - PYTHONPATH=/silk:/seamless
        - SEAMLESS_DATABASE_IP=${SEAMLESS_DATABASE_IP_MAPPED:?}
        - SEAMLESS_DATABASE_PORT=${DATABASE_PORT:?}
        - SEAMLESS_READ_BUFFER_SERVERS=${SEAMLESS_READ_BUFFER_SERVERS_MAPPED:?}
        - SEAMLESS_WRITE_BUFFER_SERVER=${SEAMLESS_WRITE_BUFFER_SERVER_MAPPED:?}
        - ASSISTANT_HOST=0.0.0.0
        - ASSISTANT_PORT=${SEAMLESS_ASSISTANT_PORT:?}
        - DOCKER_IMAGE=seamless-devel
        - DOCKER_VERSION=${DOCKER_VERSION:-""}
  micro-assistant:
      build:
        context: ../../scripts
        dockerfile: micro-assistant.Dockerfile
      user: ${HOST_USER_ID:?}:${HOST_GROUP_ID:?}
      ports:
        - ${SEAMLESS_ASSISTANT_PORT:?}:${SEAMLESS_ASSISTANT_PORT:?}
      environment:
        - SEAMLESS_DATABASE_IP=${SEAMLESS_DATABASE_IP_MAPPED:?}
        - SEAMLESS_DATABASE_PORT=${DATABASE_PORT:?}
        - SEAMLESS_READ_BUFFER_SERVERS=${SEAMLESS_READ_BUFFER_SERVERS_MAPPED:?}
        - SEAMLESS_WRITE_BUFFER_SERVER=${SEAMLESS_WRITE_BUFFER_SERVER_MAPPED:?}
        - ASSISTANT_HOST=0.0.0.0
        - ASSISTANT_PORT=${SEAMLESS_ASSISTANT_PORT:?}
  mini-assistant-devel:
      build:
        context: ../../scripts
        dockerfile: mini-assistant-devel.Dockerfile
      user: ${HOST_USER_ID:?}:${HOST_GROUP_ID:?}
      ports:
        - ${SEAMLESS_ASSISTANT_PORT:?}:${SEAMLESS_ASSISTANT_PORT:?}
      volumes:
        - ${SEAMLESSDIR:?}:/seamless
        - ${SEAMLESS_TOOLS_DIR:?}/tools:/home/jovyan/seamless-tools
        - ${SEAMLESS_TOOLS_DIR:?}/scripts:/home/jovyan/seamless-scripts
        - ${SEAMLESS_TOOLS_DIR:?}/seamless-cli:/home/jovyan/seamless-cli
        - ${SILKDIR:?}:/silk
        - /var/run/docker.sock:/var/run/docker.sock # Docker access
        - /tmp:/tmp  # temp dir to execute Docker transformers in
      group_add: 
        - users
        - ${DOCKER_GROUP_ID:?}
      environment:
        - SEAMLESS_TOOLS_DIR
        - PYTHONPATH=/silk:/seamless
        - SEAMLESS_DATABASE_IP=${SEAMLESS_DATABASE_IP_MAPPED:?}
        - SEAMLESS_DATABASE_PORT=${DATABASE_PORT:?}
        - SEAMLESS_READ_BUFFER_SERVERS=${SEAMLESS_READ_BUFFER_SERVERS_MAPPED:?}
        - SEAMLESS_WRITE_BUFFER_SERVER=${SEAMLESS_WRITE_BUFFER_SERVER_MAPPED:?}
        - ASSISTANT_HOST=0.0.0.0
        - ASSISTANT_PORT=${SEAMLESS_ASSISTANT_PORT:?}
        - DOCKER_IMAGE=seamless-devel
        - DOCKER_VERSION=${DOCKER_VERSION:-""}
  mini-assistant:
      group_add:
      - users
      build:
        context: ../../scripts
        dockerfile: mini-assistant.Dockerfile
      user: ${HOST_USER_ID:?}:${HOST_GROUP_ID:?}
      ports:
        - ${SEAMLESS_ASSISTANT_PORT:?}:${SEAMLESS_ASSISTANT_PORT:?}
      environment:
        - SEAMLESS_DATABASE_IP=${SEAMLESS_DATABASE_IP_MAPPED:?}
        - SEAMLESS_DATABASE_PORT=${DATABASE_PORT:?}
        - SEAMLESS_READ_BUFFER_SERVERS=${SEAMLESS_READ_BUFFER_SERVERS_MAPPED:?}
        - SEAMLESS_WRITE_BUFFER_SERVER=${SEAMLESS_WRITE_BUFFER_SERVER_MAPPED:?}
        - ASSISTANT_HOST=0.0.0.0
        - ASSISTANT_PORT=${SEAMLESS_ASSISTANT_PORT:?}
  mini-dask-assistant-devel:
      group_add:
        - users
      build:
        context: ../../scripts
        dockerfile: mini-dask-assistant-devel.Dockerfile
      user: ${HOST_USER_ID:?}:${HOST_GROUP_ID:?}
      ports:
        - ${SEAMLESS_ASSISTANT_PORT:?}:${SEAMLESS_ASSISTANT_PORT:?}
      volumes:
        - ${SEAMLESSDIR:?}:/seamless
        - ${SEAMLESS_TOOLS_DIR:?}/tools:/home/jovyan/seamless-tools
        - ${SILKDIR:?}:/silk
      environment:
        - DASK_SCHEDULER_ADDRESS=${DASK_SCHEDULER_ADDRESS:?}
        - PYTHONPATH=/silk:/seamless
        - SEAMLESS_DATABASE_IP=${SEAMLESS_DATABASE_IP_MAPPED:?}
        - SEAMLESS_DATABASE_PORT=${DATABASE_PORT:?}
        - SEAMLESS_READ_BUFFER_SERVERS=${SEAMLESS_READ_BUFFER_SERVERS_MAPPED:?}
        - SEAMLESS_WRITE_BUFFER_SERVER=${SEAMLESS_WRITE_BUFFER_SERVER_MAPPED:?}
        - ASSISTANT_HOST=0.0.0.0
        - ASSISTANT_PORT=${SEAMLESS_ASSISTANT_PORT:?}
        - DOCKER_IMAGE=seamless-devel
        - DOCKER_VERSION=${DOCKER_VERSION:-""}
